import { Housinglocation } from '../../app/housinglocation';

export const getHomeList = (baseUrl: string): Housinglocation[] => {
  return [
    {
      id: '0',
      name: 'Acme Fresh Start Housing',
      city: 'Chicago',
      state: 'IL',
      photo: `https://imgs.search.brave.com/g1vkDWPVjYQGPstxuy12RWTuOuhcSVJXeDsLLDagUmo/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9oaXBz/LmhlYXJzdGFwcHMu/Y29tL2htZy1wcm9k/L2ltYWdlcy9kZWZp/bmljaW9uLWhpc3Rv/cmlhLWRlLWxvZnQt/My0xNTI3MDcxNzk2/LmpwZz9yZXNpemU9/OTgwOio`,
      availableUnits: 4,
      wifi: true,
      laundry: true,
    },
    {
      id: '1',
      name: 'A113 Transitional Housing',
      city: 'Santa Monica',
      state: 'CA',
      photo: `https://imgs.search.brave.com/g1vkDWPVjYQGPstxuy12RWTuOuhcSVJXeDsLLDagUmo/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9oaXBz/LmhlYXJzdGFwcHMu/Y29tL2htZy1wcm9k/L2ltYWdlcy9kZWZp/bmljaW9uLWhpc3Rv/cmlhLWRlLWxvZnQt/My0xNTI3MDcxNzk2/LmpwZz9yZXNpemU9/OTgwOio`,
      availableUnits: 0,
      wifi: false,
      laundry: true,
    },
    {
      id: '2',
      name: 'Warm Beds Housing Support',
      city: 'Juneau',
      state: 'AK',
      photo: `https://imgs.search.brave.com/g1vkDWPVjYQGPstxuy12RWTuOuhcSVJXeDsLLDagUmo/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9oaXBz/LmhlYXJzdGFwcHMu/Y29tL2htZy1wcm9k/L2ltYWdlcy9kZWZp/bmljaW9uLWhpc3Rv/cmlhLWRlLWxvZnQt/My0xNTI3MDcxNzk2/LmpwZz9yZXNpemU9/OTgwOio`,
      availableUnits: 1,
      wifi: false,
      laundry: false,
    },
    {
      id: '3',
      name: 'Homesteady Housing',
      city: 'Chicago',
      state: 'IL',
      photo: `https://imgs.search.brave.com/g1vkDWPVjYQGPstxuy12RWTuOuhcSVJXeDsLLDagUmo/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9oaXBz/LmhlYXJzdGFwcHMu/Y29tL2htZy1wcm9k/L2ltYWdlcy9kZWZp/bmljaW9uLWhpc3Rv/cmlhLWRlLWxvZnQt/My0xNTI3MDcxNzk2/LmpwZz9yZXNpemU9/OTgwOio`,
      availableUnits: 1,
      wifi: true,
      laundry: false,
    },
    {
      id: '4',
      name: 'Happy Homes Group',
      city: 'Gary',
      state: 'IN',
      photo: `https://imgs.search.brave.com/g1vkDWPVjYQGPstxuy12RWTuOuhcSVJXeDsLLDagUmo/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9oaXBz/LmhlYXJzdGFwcHMu/Y29tL2htZy1wcm9k/L2ltYWdlcy9kZWZp/bmljaW9uLWhpc3Rv/cmlhLWRlLWxvZnQt/My0xNTI3MDcxNzk2/LmpwZz9yZXNpemU9/OTgwOio`,
      availableUnits: 1,
      wifi: true,
      laundry: false,
    },
    {
      id: '5',
      name: 'Hopeful Apartment Group',
      city: 'Oakland',
      state: 'CA',
      photo: `https://imgs.search.brave.com/g1vkDWPVjYQGPstxuy12RWTuOuhcSVJXeDsLLDagUmo/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9oaXBz/LmhlYXJzdGFwcHMu/Y29tL2htZy1wcm9k/L2ltYWdlcy9kZWZp/bmljaW9uLWhpc3Rv/cmlhLWRlLWxvZnQt/My0xNTI3MDcxNzk2/LmpwZz9yZXNpemU9/OTgwOio`,
      availableUnits: 2,
      wifi: true,
      laundry: true,
    },
    {
      id: '6',
      name: 'Seriously Safe Towns',
      city: 'Oakland',
      state: 'CA',
      photo: `https://imgs.search.brave.com/g1vkDWPVjYQGPstxuy12RWTuOuhcSVJXeDsLLDagUmo/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9oaXBz/LmhlYXJzdGFwcHMu/Y29tL2htZy1wcm9k/L2ltYWdlcy9kZWZp/bmljaW9uLWhpc3Rv/cmlhLWRlLWxvZnQt/My0xNTI3MDcxNzk2/LmpwZz9yZXNpemU9/OTgwOio`,
      availableUnits: 5,
      wifi: true,
      laundry: true,
    },
    {
      id: '7',
      name: 'Hopeful Housing Solutions',
      city: 'Oakland',
      state: 'CA',
      photo: `https://imgs.search.brave.com/g1vkDWPVjYQGPstxuy12RWTuOuhcSVJXeDsLLDagUmo/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9oaXBz/LmhlYXJzdGFwcHMu/Y29tL2htZy1wcm9k/L2ltYWdlcy9kZWZp/bmljaW9uLWhpc3Rv/cmlhLWRlLWxvZnQt/My0xNTI3MDcxNzk2/LmpwZz9yZXNpemU9/OTgwOio`,
      availableUnits: 2,
      wifi: true,
      laundry: true,
    },
    {
      id: '8',
      name: 'Seriously Safe Towns',
      city: 'Oakland',
      state: 'CA',
      photo: `https://imgs.search.brave.com/g1vkDWPVjYQGPstxuy12RWTuOuhcSVJXeDsLLDagUmo/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9oaXBz/LmhlYXJzdGFwcHMu/Y29tL2htZy1wcm9k/L2ltYWdlcy9kZWZp/bmljaW9uLWhpc3Rv/cmlhLWRlLWxvZnQt/My0xNTI3MDcxNzk2/LmpwZz9yZXNpemU9/OTgwOio`,
      availableUnits: 10,
      wifi: false,
      laundry: false,
    },
    {
      id: '9',
      name: 'Capital Safe Towns',
      city: 'Portland',
      state: 'OR',
      photo: `https://imgs.search.brave.com/g1vkDWPVjYQGPstxuy12RWTuOuhcSVJXeDsLLDagUmo/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9oaXBz/LmhlYXJzdGFwcHMu/Y29tL2htZy1wcm9k/L2ltYWdlcy9kZWZp/bmljaW9uLWhpc3Rv/cmlhLWRlLWxvZnQt/My0xNTI3MDcxNzk2/LmpwZz9yZXNpemU9/OTgwOio`,
      availableUnits: 6,
      wifi: true,
      laundry: true,
    },
  ];
};
