GET http://localhost:3000/api/categories

###

GET http://localhost:3000/api/note-valid-route

###

POST http://localhost:3000/api/categories
Content-Type: application/json

{
  "name": "Other"
}


###

GET http://localhost:3000/api/posts

###

POST http://localhost:3000/api/posts
Content-Type: application/json

{
  "title": "Post Test Postman",
  "image": "https://images.unsplash.com/photo-1556276797-5086e6b45ff9?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=600&ixid=eyJhcHBfaWQiOjF9&ixlib=rb-1.2.1&q=80&w=800",
  "description": "Description from Postman",
  "category": "1"
}

###
POST http://localhost:3000/api/posts/a47f5337-16f2-49a0-bc14-e97bb24b56a9/comments
Content-Type: application/json

{
  "author": "MFEE",
  "content": "Good content"
}

###

PATCH http://localhost:3000/api/posts/a47f5337-16f2-49a0-bc14-e97bb24b56a9
Content-Type: application/json

{
  "title": "Test Postman New",
  "description": "Description from Postman"
}

###
DELETE http://localhost:3000/api/posts/a47f5337-16f2-49a0-bc14-e97bb24b56a9

###